### ISSUE TITLE
Essence roadmap

### ISSUE THREAD

**Issue by raulmatei** [PearlVentures/Essence#37]
Our plans for the next period is:

- [ ] support for React v0.14.x - #36 
- [ ] close all resolved issues
- [ ] release on NPM (minor version bump)
- [ ] solve and close all unresolved issues
- [ ] fix styling inconsistencies with Google Material Design specs
- [ ] move build process to Webpack && Babel (we're still using old stuff on this one)
- [ ] break Essence in smaller modules
  - [ ] react-essence-core (block, divider, highlighter, ripple, text)
  - [ ] react-essence-app-bar
  - [ ] react-essence-bottom-sheets
  - [ ] react-essence-button
  - [ ] react-essence-card
  - [ ] react-essence-chip
  - [ ] react-essence-date-picker
  - [ ] react-essence-dialog
  - [ ] react-essence-icons
  - [ ] react-essence-image
  - [ ] react-essence-text-fields
  - [ ] react-essence-list
  - [ ] react-essence-menu
  - [ ] react-essence-navigation
  - [ ] react-essence-paper
  - [ ] react-essence-progress
  - [ ] react-essence-slider
  - [ ] react-essence-snack-bar
  - [ ] react-essence-switch
  - [ ] react-essence-tab
  - [ ] react-essence-toast
  - [ ] react-essence-toolbar

**Comment by hetmann** [comment]
Hi @CoveTechnologyAus 

Thanks for the positive feedback, I think next week we would finish the **essence-toolbar** component and starting build the **date-picker** / **hour-picker**. 

> **NOTE**: If you are wondering why is taking this so long is that we are in the process to move all our components `LESS` styles from `display: block` to `display: flex`

**Comment by JasonWeise** [comment]
That's awesome news, we will wait for essence-toolbar, we will be able to start with that and wait for the date/hour picker... keep up the great work, from the "mini" projects I have created to test this framework, I think it is definitely the goods :+1:

**Comment by hetmann** [comment]
Hi @JasonWeise 

I'd manage to finish building the **essence-toolbar** so you can test it today or this weekend :)
You can visit the component at NPM https://www.npmjs.com/package/essence-toolbar

So you can install and use it as follows:
```
npm install essence-toolbar
```

```jsx
import ToolBar from 'essence-toolbar';

class ToolBarTest extends React.Component {
    render() {
        return(
            <div>
                <ToolBar>This is a simple toolbar</ToolBar>
                <ToolBar floating={true}>This is a floating toolbar</ToolBar>
                <ToolBar bottom={true}>This is a bottom fixed toolbar</ToolBar>
                <ToolBar noShadow={true}>This is a toolbar without shadow</ToolBar>
            </div>
        );
    }
};
```

With options:
- **floating**: boolean - default `false`
- **bottom**: boolean - default `false`
- **noShadow**: boolean - default `false`

or you can combine `bottom: true` and `noShadow: true`

> **NOTE**: next week we will finish the `essence-date-picker` & `essence-hour-picker`
